import express from "express";
import Resume from "../../server/models/Resume.js";
import User from "../../server/models/User.js";
import { authMiddleware } from "../../server/middleware/authMiddleware.js";

const router = express.Router();

router.post("/generate", (req, res) => {
  const { name, skills, experience } = req.body;

  const content = `
===============================
         ${name?.toUpperCase() || "USER"}
===============================

Skills:
${skills}

Experience:
${experience}

===============================
Generated by AI Resume Builder
  `;

  
  res.json({ content });
});

router.get("/history", authMiddleware, async (req, res) => {
  try {
    const userId = req.user.id;

    const resumes = await Resume.find({ userId }).sort({ createdAt: -1 });

    res.json(resumes);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});


export default router;