import express from "express";
import User from "../models/User.js";
import { authMiddleware } from "../middleware/authMiddleware.js";

const router = express.Router();

router.post("/generate", authMiddleware, async (req, res) => {
  try {
    const { name, skills, experience } = req.body;

    const user = await User.findById(req.userId);

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    if (user.credits <= 0) {
      return res.status(400).json({ message: "No credits left" });
    }

    
    user.credits -= 1;

    const content = `
===============================
         ${name?.toUpperCase() || "USER"}
===============================

Skills:
${skills}

Experience:
${experience}

===============================
Generated by AI Resume Builder
    `;

    
    user.resumes.push({
      content,
      createdAt: new Date()
    });

    await user.save();

    res.json({
      content,
      credits: user.credits
    });

  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

router.get("/history", authMiddleware, async (req, res) => {
  try {
    const user = await User.findById(req.userId);

    res.json(user.resumes || []);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;