import express from "express";
import User from "../models/User.js";
import { authMiddleware } from "../middleware/authMiddleware.js";

const router = express.Router();

router.post("/generate", (req, res) => {
  const { name, skills, experience } = req.body;

  const content = `
===============================
         ${name?.toUpperCase() || "USER"}
===============================

Skills:
${skills}

Experience:
${experience}

===============================
Generated by AI Resume Builder
  `;

  
  res.json({ content });
});

router.post("/someRoute", handler);

router.get("/history", authMiddleware, async (req, res) => {
  try {
    const userId = req.userId;

    const user = await User.findById(userId);

    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    res.json({
      credits: user.credits, 
      resumes: user.resumes || [] 
    });

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
export default router;